import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      id: 'introduction',
      type: 'doc',
      label: 'Introduction',
    },
    {
      type: "category",
      label: "Docs",
      collapsed: false,
      items: [
        {
          id: 'docs/getting-started',
          type: 'doc',
          label: 'Getting Started',
        },
        {
          id: 'docs/usage',
          type: 'doc',
          label: 'Usage',
        },
        {
          id: 'docs/positioning',
          type: 'doc',
          label: 'Positioning',
        },
        {
          id: 'docs/calendar-type',
          type: 'doc',
          label: 'Calendar Type',
        },
        {
          id: 'docs/i18n',
          type: 'doc',
          label: 'i18n',
        },
        {
          id: 'docs/customization',
          type: 'doc',
          label: 'Customization',
        },
        {
          id: 'docs/theming',
          type: 'doc',
          label: 'Theming',
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          id: 'api/component',
          type: 'doc',
          label: 'Date & Date-Time Picker',
        },
        {
          id: 'api/calendar',
          type: 'doc',
          label: 'Calendar',
        },
        {
          id: 'api/days-calendar',
          type: 'doc',
          label: 'Days Calendar',
        },
        {
          id: 'api/months-calendar',
          type: 'doc',
          label: 'Months Calendar',
        },
        {
          id: 'api/years-calendar',
          type: 'doc',
          label: 'Years Calendar',
        },
        {
          id: 'api/time-picker',
          type: 'doc',
          label: 'Time Picker',
        },
        {
          id: 'api/date-field',
          type: 'doc',
          label: 'Date Field',
        },
      ],
    },
  ],
};

export default sidebars;
